name: Build & Publish

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  build:
    name: 🔨 Build
    runs-on: windows-latest

    steps:
    - name: ✅ Checkout repository
      uses: actions/checkout@v7
    
    - name: 🆙 Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: 🆙 Setup NuGet
      uses: NuGet/setup-nuget@v2.0.1
      
    - name: 🧷 Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: 🪄 Create Build Directory
      run: mkdir build
      
    - name: 🔁 Restore Packages
      run: nuget restore BloodRushClient.sln

    - name: 🔨 Build Solution
      run: |
        msbuild.exe BloodRushClient.sln /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"
        
    - name: ⬆️ Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: "./BloodRushClient/bin/Release"
  
  publish:
    name: 🚀 Publish
    runs-on: windows-latest
    permissions: write-all
    needs: build
    if: success()
    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v7

      - name: ✅ Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: Build
          path: "./BloodRushClient/bin/Release"

      - name: 🔁 Generate as build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "build-${{ github.run_number }}"
          prerelease: false
          title: "Build ${{ github.run_number }}"
          files: |
            ./BloodRushClient/bin/Release/*.exe
            ./BloodRushClient/bin/Release/*.config